name = "UnfoldCDL"
uuid = "dbccb84b-e307-4652-ba5b-383ef6e27386"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastaLoader = "139838d8-4077-4d8a-94e1-e6dd554a184c"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimDNA = "f325a362-c78e-481f-886d-076c680a7e4a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
CUDA = "3.12.0"
CairoMakie = "0.9.2"
ColorSchemes = "3.19.0"
DataFrames = "1.4.2"
DataStructures = "0.18.13"
Distributions = "0.25.76"
DocumenterTools = "0.1"
DoubleFloats = "1.2.2"
FFTW = "1.5.0"
FastaLoader = "0.1.9"
Flux = "0.13.7"
HypothesisTests = "0.10.11"
Makie = "0.18.2"
Mustache = "1.0.14"
SimDNA = "0.1.7"
StaticArrays = "1.5.9"
StatsBase = "0.33.21"
Zygote = "0.6.49"
julia = "1.8.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
